version: "3.7"
services:
  mysqldb:
    build:
      context: .
      dockerfile: DockerfileMysql
    container_name: mysqldb8zup
    image: mysqldb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: zup
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_INIT_COMMAND: "SET GLOBAL sql_mode = '';"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql
      - ./path/to/init.sql:/docker-entrypoint-initdb.d/init.sql

  zup-app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
       VERSION: ${TAG}
    image: walysonsilva/zup-app:${TAG}  # A imagem deve ser referenciada corretamente
    container_name: zup-app
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker 
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/zup
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
