name: Build code, run unit test, run SAST, SCA, DAST security scans

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run unit tests and SAST scan on the source code
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Navigate to project directory
        run: cd zup/Zup

      - name: Build and Test with Maven
        run: mvn -B clean verify sonar:sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  security:
    runs-on: ubuntu-latest
    needs: build
    name: Run the SCA scan on the source code
    steps:
      - uses: actions/checkout@v3

      - name: Navigate to project directory
        run: cd zup/Zup

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@v2
        with:
          args: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  zap_scan:
    runs-on: ubuntu-latest
    needs: security
    name: Run DAST scan on the web application
    steps:
      - uses: actions/checkout@v3

      - name: Navigate to project directory
        run: cd zup/Zup

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://localhost:8080'  # Adjust this to match your application URL
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Stop Spring Boot applications
        run: |
          pkill -f 'mvn spring-boot:run'
